import React from "react";
import Meta from "../components/Meta";
import BreadCrumb from "../components/BreadCrumb";
import Container from "../components/Container";
const TermsAndCondition = () => {
  return (
    <div>
      <>
        <Meta title={"Terms & Condition"} />
        <BreadCrumb title="Terms & Condition" />
        <div className="bg-[#fbfbfc]">
          <Container>
            <section class="py-4 mx-3 pb-8">
              <div class="">
                {/* <h2 class="text-3xl font-bold leading-tight text-black sm:text-4xl lg:text-5xl">Frequently Asked Questions</h2> */}

                <div class="flow-root mt-12 sm:mt-16">
                  <div class="divide-y divide-gray--200 -my-9">
                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        TERMS & Condition
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        These Terms of Use together with the applicable policies
                        which are incorporated herein by way of reference (“
                        Terms”) govern the access or use of the website
                        https://sajivanayurveda.in/ (“ Website”). The Website is
                        an online service owned, operated and managed by
                        Sajivanayurveda .
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Terms of use
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        The Website is available for You together with all the
                        content, tools, facilities, and services made available
                        through the Website (collectively “the Service”).
                        Therefore, please read these Terms very carefully.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        By clicking the box indicating acceptance of these
                        Terms, you are indicating that you have read and
                        understood these Terms and agree that these Terms
                        constitute a legal and binding agreement between the
                        User (“You”, “User”, “Patient”, or “Yours”) and
                        sajivanayurveda , Third flor – 313, Kalasagar Shopping
                        Hub, Nr. Sattadhar Cross Road, Ghatlodia, Ahmedabad –
                        380061 (SAJIVAN AYURVEDA).
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        If You do not understand the Terms or if these Terms or
                        any part of these Terms is not acceptable to You, please
                        do not access or use the Service or any part thereof. In
                        these Terms, “You” / “Yours” / “Yourself” denotes the
                        natural person who accesses/uses the Service or any part
                        thereof.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        We reserve the right to update or modify these Terms at
                        any time in our sole discretion without any prior notice
                        to You. If we update or modify these Terms, we will post
                        the revised version of these Terms on the Website and
                        such revision shall become effective immediately on such
                        posting. It is Your responsibility to review these Terms
                        periodically for updates/modifications. Your continued
                        access or use of any of the Service after any revision
                        becomes effective shall be deemed to constitute your
                        acceptance and agreement to be bound by the revised
                        Terms.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        In terms of the Information Technology Act, 2000, this
                        document is an electronic record. Being generated by a
                        computer system it does not require any physical or
                        digital signatures.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        This document is published in accordance with the
                        provisions of Rule 3 (1) of the Information Technology
                        (Intermediaries Guidelines) Rules, 2011 that require
                        publishing the rules and regulations, privacy policy and
                        Terms of Use for access or usage of the Website or the
                        application ‘sajivanayurveda.in’.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Ownership and Intellectual Property Rights
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        We own all copyright, trademarks, domain names and other
                        intellectual property rights in or related to the
                        Service and all its various components. Except for Your
                        personal data and information, all information, content,
                        and material contained on the Website and/or Service is
                        our intellectual property. No information, content or
                        material from any part of the Service may be copied,
                        reproduced, republished, uploaded, recorded, posted,
                        transmitted or distributed in any way (including by
                        using any automated programs, software, or any other
                        method of screen scraping), except for Your personal and
                        non-commercial use, without Our express written
                        permission.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Eligibility & Registration
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. The access/use of the Service is meant only for
                        persons who are competent to contract as per Indian law.
                        If You are not ‘competent to contract’ as per Indian law
                        (i.e. if You have not attained the age of majority
                        according to the law to which You are subject, if You
                        are not of sound mind or if You are disqualified from
                        contracting by any law to which You are subject or any
                        other provision as per Contract Law), You should not
                        register or access/use the Service or any part thereof.
                        If the law applicable to You does not allow You to
                        receive the Services in Your territory, you should not
                        use this service. If You are the parent/legal
                        guardian/authorized person acting on behalf of a
                        patient, You should disclose the same to us and by
                        registering with us or accessing/using the Service on
                        behalf of Your ward, You affirm that You have the full
                        and proper authority to represent the patient and accept
                        these Terms on his/her behalf.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. Once You successfully log in to the Website, you have
                        to provide certain information about Yourself as
                        requested when You attempt to register with Us and start
                        using the Service. You may be required to authenticate
                        Your identity using a one-time password (“OTP”) as a
                        confirmation code, which will be transmitted to Your
                        mobile number provided to us when You seek to register
                        with Us through the short message service (“SMS”). If
                        You cannot provide the OTP when required to do so or the
                        authentication through the OTP fails, you may not be
                        able to register with Us and/or avail of the Service.
                        However, you may still be able to access and use the
                        Service always subject to these Terms.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        3. When You register with Us and/or access or use the
                        Service, You confirm that You have provided accurate,
                        current and complete information about Yourself and that
                        You will keep all such information current, complete and
                        accurate at all times for as long as You use the
                        Service. All the data and information that You provide
                        or that is collected from Your access/use of the Service
                        shall be treated and protected in accordance with our
                        Privacy Policy https://sajivanayurveda.in/ which is
                        deemed a part of these Terms.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        4. Your registration with Us and/or Your right to access
                        the Service is personal to You and You may not transfer
                        this to anyone else. You may not use anyone else’s
                        account at any time. You will be solely responsible for
                        any and all activities that occur under Your account
                        with Us and We will not be liable for any loss or damage
                        that may occur as a result of someone else using the
                        Service through Your account with Us or obtaining Your
                        personal information by any device or system, either
                        with or without Your knowledge. If You become aware of
                        any unauthorized use of Your account with Us, please
                        notify Us by writing to “sajivanayurveda.in” with the
                        title “Unauthorized Use of Account” and We will initiate
                        action to stop further access under the said account.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        5. We reserve the right to terminate Your registration
                        and / or refuse to register You or to provide You with
                        access to the Service, without notice, if We have
                        reasonable cause to believe that You are in violation of
                        or are likely to violate these Terms.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Promotional Communications
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        “We may also send you other information about us, the
                        Website, our other websites, products, sales promotions,
                        our newsletters, SMS updates, anything relating to other
                        companies in our group or our business partners. If you
                        would prefer not to receive any of this additional
                        information as detailed in this paragraph (or any part
                        of it) please click the “unsubscribe” link in any email
                        that we send to you or register as a Do Not Disturb
                        user. Within 7 working days (days which are neither (i)
                        a Saturday or Sunday, nor (ii) a public holiday anywhere
                        in India) of receipt of your instruction, we will cease
                        to send you information as requested. In case of any
                        clarity, you can contact our Customer support service”.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Grant of License & Reservation of Rights
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. We grant You a non-exclusive, personal,
                        non-transferable, revocable, right and license, subject
                        always to these Terms to access/use the Service solely
                        for Your personal, non-commercial use.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. Except for the limited rights and licenses granted to
                        You by these Terms, all rights in the Service (including
                        all intellectual property rights therein or underlying
                        the same, including in the Website and the App) are
                        reserved by Us.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        3. You do hereby grant Us a non-exclusive, worldwide,
                        perpetual, irrevocable, royalty-free, sub-licensable
                        right to exercise the copyright, publicity, and database
                        rights You have in Your information, in any media now
                        known or not currently known, with respect to Your
                        information to enable Us to use the information for the
                        purpose of providing the Services.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Nature of Service & Limitations
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. No doctor-patient relationship between Us and the
                        User.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. We do not provide medical consultation. We provide a
                        platform to place orders for medicine on Our Website
                        (“Products”).
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        3. Any products or services that we are providing is
                        prepared after consulting with a team of Ayurvedic
                        experts.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        4. To enrich and improve Your experience, qualified
                        ayurvedic consultants designed the questionnaires that
                        help to indicate the treatment that can be followed.
                        Please note that it is not medical advice.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        5. Ayurvedic practitioners have signed/accepted
                        contracts with Us and represented to Us that they are
                        duly qualified to practice and sell medicine in India
                        and are enrolled on the medical register in one of the
                        states in India. While We make reasonable inquiries to
                        confirm the veracity of this representation made to Us
                        by the Ayurvedic Practitioners, We shall not be
                        responsible for any misrepresentation or fraud in this
                        regard.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        6. The use of the Products or Services does not create a
                        doctor/patient relationship between You and Us, nor is
                        it for any kind of medical emergencies or for
                        life-threatening conditions or for when you need acute
                        care.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        7. You should continue to consult with Your physician
                        and any other health care professionals as needed /
                        recommended. You should seek emergency help or follow-up
                        care when recommended by your Medical Practitioner or
                        when You are of the opinion that such help or care is
                        prudent in Your sole opinion.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        No Diagnostic / Medical / Clinical Tests or Service
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. We do not provide diagnostic or medical or clinical
                        test Services. We may provide you the third party
                        diagnostic laboratories on request. The medical/clinical
                        test or diagnostic Services are provided to You directly
                        by the concerned laboratories or centers. We make no
                        representations or claims, including as to the accuracy
                        or quality, of the tests or results obtained by You from
                        diagnostic laboratories/centers and shall not be
                        responsible or liable for any defect or deficiency in
                        the Services provided to You by a diagnostic
                        laboratory/center.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. Diagnostic laboratories/centers we will provide you
                        are duly certified/licensed and have the necessary
                        equipment, qualified personnel, experience and expertise
                        to provide their Services to You in India. While We make
                        reasonable inquiries to confirm the veracity of this
                        representation made to Us by the diagnostic
                        laboratories/centers, We shall not be responsible for
                        any misrepresentation or fraud in this regard.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Use of Service
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. To use the Service hassle-free, you should be 18+.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. You should belong to the same state from where we are
                        operating to take the maximum benefit out of service.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        3. You agree to have a legal and binding agreement with
                        us and ready to comply with our terms of use.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        4. You agree to use the only in accordance with these
                        Terms and all applicable laws. You may not use the
                        Service in any manner that could damage, disable,
                        overburden, or impair Our computer systems or interfere
                        with any other party’s use and enjoyment of any Service.
                        You should not attempt to gain unauthorized access to
                        any Service. You may not obtain or attempt to obtain any
                        materials or information through any means not
                        intentionally made available through the Service.
                      </p>
                      <ul class="mt-3 font-normal text-gray-700">
                        5. Without prejudice to the above, you agree not to
                        host, display, upload, modify, publish, transmit, update
                        or share any information that:
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          1. belongs to another person and to which You do not
                          have any right to;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          2. is grossly harmful, harassing, blasphemous
                          defamatory, obscene, pornographic, pedophilic,
                          libelous, invasive of another’s privacy, hateful, or
                          racially, ethnically objectionable, disparaging,
                          relating or encouraging money laundering or gambling,
                          or otherwise unlawful in any manner whatever;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          3. harm minors in any way;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          4. infringes any patent, trademark, copyright or other
                          proprietary rights;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          5. violates any law for the time being in force;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          6. deceives or misleads the addressee about the origin
                          of such messages or communicates any information which
                          is grossly offensive or menacing in nature;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          7. impersonates another person:
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          8. contain software viruses or any other computer
                          code, files or programs designed to interrupt, destroy
                          or limit the functionality of any computer resource;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          9. threatens the unity, integrity, defense, security
                          or sovereignty of India, friendly relations with
                          foreign states, or public order or causes incitement
                          to the commission of any cognizable offense or
                          prevents investigation of any offense or is insulting
                          any other nation;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          10. You are solely responsible for all information You
                          transmit or share, we are not obliged to monitor the
                          same. However, We reserve the right to review any
                          information or materials You share and to remove
                          (without notice to You) any information or materials
                          that We find, in our sole discretion, violates any
                          applicable law or these Terms. To this extent, you
                          hereby authorize us to review all information. In the
                          event of non-compliance with the Terms, we may
                          (without notice to You), immediately terminate Your
                          registration with Us and/or prevent Your access or use
                          of the Service.
                        </li>
                      </ul>

                      <ul class="mt-3 font-normal text-gray-700">
                        6. are also prohibited from:
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          1. violating or attempting to violate the integrity or
                          security of the Website or its content;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          2. transmitting any information on or through the
                          Website that is disruptive or competitive to the
                          provision of Services by us;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          3. intentionally submitting on the Website any
                          incomplete, false or inaccurate information;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          4. making any unsolicited communications to other
                          users of the Website;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          5. using any engine, software, tool, agent or other
                          device or mechanism (such as spiders, robots, avatars
                          or intelligent agents) to navigate or search the
                          Website;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          6. attempting to decipher, decompile, disassemble or
                          reverse engineer any part of the Website;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          7. copying or duplicating in any manner any of the
                          content on the Website or other information available
                          from the Website;
                        </li>
                        <li class="mx-l-2 mt-3 font-normal text-gray-700">
                          8. framing or hotlinking or deep linking any content
                          on the Website.
                        </li>
                      </ul>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Payment For Service
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. Some parts of the Service are chargeable as may be
                        specified from time to time. We will tell You about
                        applicable charges for any paid Service and the payment
                        terms presented to You when You use or order a paid
                        Service are deemed part of these Terms of Use. As a
                        convenience to You, We reserve the right to suspend or
                        cancel Your order for the said Service or to not provide
                        You with the ordered Service. We shall not be
                        responsible for any Service that is not provided to You
                        if You fail to pay the applicable charges for the same.
                        Charges paid are non-refundable except in Our sole
                        discretion.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. We use a third-party payment gateway for processing
                        payments due to Us. The processing of payments will be
                        subject to the terms, conditions and privacy policies of
                        the payment gateway, in addition to these Terms. We
                        don’t control and are not liable for the security or
                        performance of the payment gateway. You agree to pay Us,
                        through the payment gateway, all charges at the rates
                        then in effect for any purchase in accordance with the
                        applicable payment terms. We reserve the right to
                        correct, or to instruct Our payment gateway to correct,
                        any errors or mistakes, even if payment has already been
                        requested or received. 3. We strive to provide the best
                        prices possible on products and services to users buying
                        or availing through the Website. However, We do not
                        guarantee that the price will be the lowest in the city,
                        region or geography. Prices and availability are subject
                        to change without notice or any consequential liability
                        on sajivanayurveda;
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Your Data and Information
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. When You register with Us and/or access the Service,
                        You will be required to provide certain personal data
                        and information about Yourself to Us. When You access or
                        use the Service, We also collect and store certain
                        information and data about You and Your access/use. Our
                        Privacy Policy which is available at
                        https://sajivanayurveda.in explains what personal
                        information and data We collect and how We treat Your
                        personal data and information and protect Your privacy.
                        The terms of Our Privacy Policy are deemed incorporated
                        in these Terms and forms a part of these Terms.
                        Therefore, please read Our Privacy Policy carefully.
                        When You access or use the Service, You consent to the
                        collection and use of Your personal data and information
                        in accordance with our Privacy Policy.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. Notwithstanding anything contained in these Terms,
                        You hereby permit Us to store all information You
                        transmit or share. You hereby permit Us to transit
                        prescriptions for medicines with Pharmacies to enable
                        them to service Your order for the drugs and medicinal
                        preparations ordered by You. Subject to the above, Your
                        medical/patient records pertaining to the Services You
                        avail through the Service shall remain Your property.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        3. While placing an order for sale of drugs / medicinal
                        preparations with Us, You fully authorize Us to share
                        Your personal details like name, address, phone number,
                        etc. as well as the medical prescription to third party
                        Pharmacy for the purpose of processing Your order. The
                        same Third Party Pharmacies may, in turn, store/use this
                        information for their internal purposes. Also, on
                        placing an order with Us, You authorize the third party
                        online pharmacies to contact You via Phone/ SMS / Email
                        for the purpose of fulfilling Your order.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        4. We are requesting Your email address, so We can send
                        You invoices for the transactions You make on
                        sajivanayurveda and also to help You refer Your friends
                        and family and therefore earn a referral bonus.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Payment For Service
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        1. Some parts of the Service are chargeable as may be
                        specified from time to time. We will tell You about
                        applicable charges for any paid Service and the payment
                        terms presented to You when You use or order a paid
                        Service are deemed part of these Terms of Use. As a
                        convenience to You, We reserve the right to suspend or
                        cancel Your order for the said Service or to not provide
                        You with the ordered Service. We shall not be
                        responsible for any Service that is not provided to You
                        if You fail to pay the applicable charges for the same.
                        Charges paid are non-refundable except in Our sole
                        discretion.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        2. We use a third-party payment gateway for processing
                        payments due to Us. The processing of payments will be
                        subject to the terms, conditions and privacy policies of
                        the payment gateway, in addition to these Terms. We
                        don’t control and are not liable for the security or
                        performance of the payment gateway. You agree to pay Us,
                        through the payment gateway, all charges at the rates
                        then in effect for any purchase in accordance with the
                        applicable payment terms. We reserve the right to
                        correct, or to instruct Our payment gateway to correct,
                        any errors or mistakes, even if payment has already been
                        requested or received.
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        3. We strive to provide the best prices possible on
                        products and services to users buying or availing
                        through the Website. However, We do not guarantee that
                        the price will be the lowest in the city, region or
                        geography. Prices and availability are subject to change
                        without notice or any consequential liability on
                        sajivanayurveda;
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Changes to Service
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        We reserve the sole and complete discretion with respect
                        to the operation of the Service and We may add, modify,
                        suspend or discontinue any functionality or feature of
                        the Service or any of the Services provided by Us
                        without any notice to You.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Third-Party Links and Advertisements
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        The Service may contain links to third-party websites
                        and third-party advertisements, that are not maintained
                        or controlled by Us. Third party links and
                        advertisements are provided for Your convenience only
                        and do not imply an endorsement or any representation or
                        warranty by Us to content, goods or services that may be
                        offered by these third parties. When You click on any of
                        these third party links, You are leaving the Service and
                        will be subject to the terms of use and privacy and
                        security policies of the third party site. You link to
                        any such third party website entirely at Your own risk.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Warranty Disclaimer
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        You acknowledge and agree that Your use of the Service
                        is solely at Your own risk and that You assume full
                        responsibility for all risks associated therewith. All
                        information, products or services contained on or
                        provided through the Service are provided “as is”,
                        without any warranty of any kind, express or implied. We
                        do not make any warranty or representation as to the
                        quality, quantity, potency, purity, standard, nature or
                        manner of performance of any of the information,
                        products or services contained on or provided through
                        the Service. We hereby disclaim, to the maximum extent
                        permitted by applicable law, all representations and
                        warranties, express or implied, statutory or otherwise,
                        including but not limited to warranties of
                        merchantability, fitness for any particular purpose,
                        title, non-infringement, reliability, accuracy,
                        completeness, timeliness or that the availability of the
                        Service will be uninterrupted, timely, secure, or
                        error-free. The Website assumes no responsibility for
                        any damages or viruses that may infect Your computer
                        equipment or other property on account of Your access
                        to, use of, or browsing in this Website.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Limitation & Exclusion of Liability
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        To the fullest extent permitted by law, in no event will
                        We be liable for any direct, indirect, special,
                        incidental, punitive, exemplary or consequential
                        damages, whether or not We have been warned of the
                        possibility of such damages. In any event, our total
                        aggregate liability to You, if any, will not exceed the
                        charges paid to Us by you (if any) for the particular
                        Service in questions.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">Indemnity</p>
                      <p class="mt-3  font-normal text-gray-700">
                        We shall not be liable to any person for any loss or
                        damage which may arise from the use of any of the
                        information contained in any of the materials on this
                        Website. You agree to defend, indemnify and hold
                        harmless sajivanayurveda, its employees, directors,
                        officers, agents and their successors and assigns from
                        and against any and all claims, liabilities, damages,
                        losses, costs and expenses, including attorney’s fees,
                        caused by or arising out of claims based upon Your
                        actions or inactions, which may result in any loss or
                        liability to sajivanayurveda or any third party
                        including but not limited to breach of any warranties,
                        representations or undertakings or in relation to the
                        non-fulfillment of any of Your obligations under these
                        Terms or arising out of your violation of any applicable
                        laws, regulations including but not limited to
                        intellectual property rights, payment of statutory dues
                        and taxes, claim of libel, defamation, violation of
                        rights of privacy or publicity, loss of service by other
                        subscribers and infringement of intellectual property or
                        other rights.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Website feedback, user comments, and user-generated
                        content
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        All reviews, comments, feedback, postcards, suggestions,
                        ideas, and other submissions disclosed, submitted to Us
                        on or by this Website or otherwise disclosed, submitted
                        or offered in connection with Your use of this Website
                        (collectively, the “Comments”) shall be and remain our
                        property. Such disclosure, submission or offer of any
                        Comments shall constitute an assignment to us of all
                        worldwide rights, titles and interests in all copyrights
                        and other intellectual properties in the Comments. Thus,
                        we own exclusively all such rights, titles, and
                        interests and shall not be limited in any way in its
                        use, commercial or otherwise, of any Comments. We will
                        be entitled to use, reproduce, disclose, modify, adapt,
                        create derivative works from, publish, display and
                        distribute any Comments You submit for any purpose
                        whatsoever, without restriction and without compensating
                        You in any way. We are and shall be under no obligation:
                        <br /> (1) to maintain any Comments in confidence;
                        <br /> (2) to pay You any compensation for any Comments;
                        or <br />
                        (3) to respond to any Comments. You agree that any
                        Comments submitted by You to the Website will not
                        violate these Terms or any right of any third party,
                        including copyright, trademark, privacy or other
                        personal or proprietary rights (s), and will not cause
                        injury to any person or entity. You further agree that
                        no Comments submitted by You to the Website will be or
                        contain libelous or otherwise unlawful, threatening,
                        abusive or obscene material, or contain software
                        viruses, political campaigning, commercial solicitation,
                        chain letters, mass mailings or any form of ‘spam’. We
                        do not regularly review posted Comments but do reserve
                        the right (but not the obligation) to monitor and edit
                        or remove any Comments submitted on the Website. You
                        grant Us the right to use the name that You submit in
                        connection with any Comments. You agree not to use a
                        false email address, impersonate any person or entity,
                        or otherwise mislead as to the origin of any Comments
                        You submit. You are and shall remain solely responsible
                        for the content of any Comments You write and You agree
                        to indemnify Us and Our affiliates for all claims
                        resulting from any Comments You submit. We and Our
                        affiliates take no responsibility and assume no
                        liability for any Comments submitted by You or any third
                        party.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Termination
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        We reserve the right to suspend and/or terminate Your
                        access to the Service with or without notice if You
                        breach these Terms. Upon suspension or termination, Your
                        right to procure the Service shall immediately cease and
                        We reserve the right to remove or delete Your
                        information that is available with Us, including but not
                        limited to account details. Such termination will be
                        without any liability to sajivanayurveda.in Upon
                        termination, You must promptly destroy all materials
                        downloaded or otherwise obtained from this Website, as
                        well as all copies of such materials, however, made. Our
                        right to any Comments shall survive such termination.
                        Any such termination shall not cancel your obligation to
                        pay for the Service already obtained through the Website
                        or affect any liability that may have arisen under these
                        Terms.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">Notices</p>
                      <p class="mt-3  font-normal text-gray-700">
                        All notices to Us shall be in writing and shall be made
                        via e-mail to sajivanayurveda.in or other email address
                        as notified in these Terms and all notices to You shall
                        be made through the Service, via e-mail to the e-mail
                        address You provide at the time of your registration or
                        to your communication device registered with Us.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Governing Law and Jurisdiction
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        The interpretation of these Terms and the resolution of
                        any dispute relating to Your access or use of the
                        Service shall be governed by the laws of India subject
                        to the exclusive jurisdiction of Courts in Ahmedabad.
                        All disputes will be subject to arbitration in Ahmedabad
                        in English by a single arbitrator appointed by us under
                        the Arbitration and Conciliation Act, 1996. Each party
                        to the arbitration shall bear its own cost.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Miscellaneous
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        If any term or provision of these Terms shall be
                        declared invalid by a court of competent jurisdiction,
                        then such provision will be interpreted, construed, or
                        reformed to the extent reasonably required to render it
                        valid, enforceable, and consistent with the original
                        intent underlying such provision and the remainder of
                        these Terms shall remain in full force and effect,
                        according to its terms. The failure to exercise or
                        enforce any right or provision of these Terms does not
                        constitute a waiver of such right or provision. Headings
                        are for reference purposes only and in no way define,
                        limit, construe or describe the scope or extent of such
                        clause. Your right to use the Service is personal to You
                        and You shall not assign or transfer in any manner any
                        of Your rights, obligations or interest in these Terms
                        or Your subscription to any third party. We may freely
                        assign our rights and obligations hereunder. Should
                        there be any conflict between these Terms and any other
                        notice/communication, the terms and conditions set forth
                        in these Terms shall prevail, to the extent of such
                        conflict. These Terms (including the Privacy Policy and
                        other notices on the Website which are incorporated and
                        deemed part of these Terms), constitute the entire
                        agreement between Us and supersedes all prior agreements
                        regarding the subject matter hereof. When You use the
                        Service and provide any information on or through the
                        Service; or when You click any of the buttons available
                        on the Website or when You send an e-mail to Us, you are
                        communicating with Us through electronic records. You
                        hereby consent that such electronic records, whether
                        sent by You or automatically generated by the computer
                        system when You click on any of the buttons available on
                        the Website or the Service, shall be deemed to be
                        communications sent in writing by You.
                      </p>
                    </div>

                    <div class="py-9">
                      <p class="text-xl font-semibold text-black">
                        Grievance Redressal
                      </p>
                      <p class="mt-3  font-normal text-gray-700">
                        If You have any concern or grievance or complaint with
                        respect to the Service, please e-mail us at
                        sajivanayurveda.in and We will study the matter and take
                        such action as we deem appropriate under the
                        circumstances. I have read and understood these Terms of
                        Use (including the Privacy Policy and other notices on
                        the Website) and agree to all of the provisions
                        contained therein
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </Container>
        </div>

      </>
    </div>
  );
};

export default TermsAndCondition;
// Simulated content (normally this would be in a separate file)
